[Main]
RealAppId=0
FakeAppId=480
#Language=schinese
BuildId=0

[Misc]
Overlay=true
FilterLobby=false

[Interfaces]
Apps=true
Friends=true
User=true
Inventory=true
Stats=true
Storage=true
Utils=true
Workshop=false

[DLC]

[FreeTP]
Id=388